---
title: Heat waves drive orientation-dependent patterns in mortality in a bed-forming intertidal barnacle, with implications for infaunal community structure
author: Amelia V. Hesketh^1^ and Christopher D.G. Harley^1,2^
output: 
  word_document:
    reference_docx: manuscript_style.docx
---

<br/>

1. Department of Zoology, University of British Columbia, 4200-6270 University Blvd., Vancouver, BC, V6T 1Z4

2. Institute for the Oceans and Fisheries, 2202 Main Mall, Vancouver, BC, V6T 1Z4  

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

<br/>

**Open research statement**: All data have been made publicly available within Scholars Portal Dataverse under a Creative Commons 4.0 CC-BY license (URL), and all novel code required for analyses and plotting can be found in a public Github repo (URL).  


# Abstract

<br/>

Abstract here

<br/>

**Keywords**: acorn barnacles, British Columbia, heat waves, foundation species, infauna, intertidal zone, mortality, _Semibalanus cariosus_, substratum orientation, thermal refugia


# Introduction

Global temperature increases have long been recognized as a threat to organisms across ecological systems (REF). Temperature increases have been linked to species range shifts (REFS), increases in pathogen prevalence (REFS), habitat destruction (wildfire stuff?), declines in biodiversity (REFS), and large-scale mortality events (REFS - Australia? California kelp forests?).

<br/>

Increasingly, stochastic events such as heat waves are understood to pose an additional challenge to organisms (REF). At particular risk are those species with sessile lifestyles, which lack the ability to seek refuge from particularly hot or cold periods (REFS). Such species have evolved thermal tolerance mechanisms to endure adverse events like heat waves (REF) and cold snaps (REF), but their in-built safety factors to cope with these periodic events are metabolically costly to maintain (REF). Thus, species that have spent millenia fine-tuning this trade-off may not be adapted to endure particularly dramatic heat waves such as that seen during the summer of 2021 in the Pacific Northwest.

<br/>

The die-off of sessile foundation species will additionally have downstream effects on those species that they facilitate.

<br/>

Rocky shores present a good small-scale system to observe the impacts of heat waves on species and biodiversity. 

<br/>

In this study, we documented how an intense heat wave affected the survival of the thatched barnacle _Semibalanus cariosus_ and its ability to act as a facilitator of intertidal biodiversity as a habitat-former. First, we completed opportunistic mortality surveys a few months following the heat wave along a natural temperature gradient in the Salish Sea (Harley 2006??). These data were used to assess what factors might explain variation in mortality between sites, namely local air temperature, aspect, algal cover, and the timing of the low tide, and what might underly variation in mortality within any given site, namely the angle of incoming sunlight. At the across-site level, we expected that differences in higher maximum daily air temperatures would correlate with higher mortality at sites, that the effect of prevailing aspect would be significant, but vary depending on the timing of the low tide, and that higher algal cover would reduce mortality. At the within-site level, we expected that the angle of incoming sunlight would inversely vary with mortality, with a more direct (smaller) angle of light correlating with higher barnacle mortality. In addition, we report on the results of a factorial experiment that manipulated temperature via a shading treatment and the presence of barnacles via a removal treatment, which provided insight into not only how mature barnacle beds respond to differences in temperature but also the impacts of heat waves on nascent beds. We expected that shades would reduce mortality relative to unshaded plots, and that communities in shaded plots would be more diverse than those in unshaded plots, irrespective of barnacle bed presence or removal.

# Materials and Methods


## Mortality surveys


Following the Pacific Northwest heat dome in the summer of 2021, surveys of _Semibalanus cariousus_ mortality were performed over a broad geographic gradient of coastal British Columbia, primarily in the Salish Sea, (Figure 1) between 5 August 2021 and 25 August 2021. Two types of surveys were performed: mortality surveys along transects, and haphazard surveys for both mortality and substratum aspect data. In the first case, 10 m transects were haphazardly placed on shore, and then 12.7 cm square quadrats were placed along these transects at every one-metre interval, with the position randomly determined within that interval. The number of live and dead barnacles within the quadrat were enumerated, along with algal cover and, in some cases, the number of moisture-retaining Anthopleura elegantissima. This process was repeated for three transects at most sites, though only two transects were conducted at Fishboat Bay and only one at Moses Point (FB and MP, Figure 1). In the case of the second survey type, quadrats of the same size were haphazardly placed on shore on surfaces that had variable orientation and angle above the horizontal. The compass direction and angle of the substratum was recorded using the Commander Compass application (version 3.10.9 for iOS), and the number of live and dead S. cariosus, live A. elegantissima, and algal cover were recorded as before.

<br/>

Samples of _S. cariosus_ beds were taken from a subset of sites where mortality surveys were conducted to measure the diversity of the infaunal community therein. For these sample, five 15 x 15 cm samples of barnacle bed were collected (n = 8 at CC and PP) and preserved by either freezing at -10 ºC or placing in 70% ethanol until they could be counted. Samples were collected only once at the majority of sites where mortality surveys occurred between 5 August 2021 and 11 September 2021, but samples were also taken in mid-April 2021 at both CC and PP to provide information about community structure prior to warm summer conditions.

<br/>

Species within preserved samples were enumerated under a dissecting microscope and in most case identified to genus or species. Polychaete worms were identified to family, amphipods and insects to order, and platyhelminths and nematodes to phylum. Species that could not be readily identified were assigned unique codes to allow their contribution to diversity to be captured.

## Shading experiment

The shading manipulation experiment was installed on the foreshore in the traditional territory of the Songhees nation at Sahsima in Victoria, British Columbia on 16 April 2021 (latitude: 48.405784, longitude: -123.323308). The barnacle _S. cariousus_ dominates the mid-intertidal at this site along with the fucoid _Fucus distichus_, interspersed with the acorn barnacle _Balanus glandula_ and the clonal anemone _Anthopleura elegantissima_. We used a stratified random design for this experiment, factorially crossing barnacle bed removal with the presence or absence of a shade to generate four treatments: IU (intact barnacles, unshaded); IS (intact barnacles, shaded); RU (removal treatment, unshaded); RS (removal treatment, shaded). At the time of initial deployment, 12 replicates of each treatment were installed on gently sloping areas of southwest-facing shore where S. cariosus was dominant and at a shore level of 1.22 ± 0.19 (mean ± SE) above chart datum.

<br/>

25 x 25 cm area, 5 cm high shades were fabricated from a two-sided cage of PVC-coated steel fencing (2.54 cm mesh size; McMaster-Carr, Elmhurst, IL, USA) with Vexar mesh (6.4 mm mesh size; Aqua-Pacific Wire Mesh & Supply Ltd., Nanaimo, BC, Canada) zip-tied on the top of the cage to limit the sunlight (and heat) reaching underlying plots. Shades were attached to the substratum by zip-tying the cages to eye-bolts drilled into the bedrock. Unshaded plots areas were demarcated using lag bolts.

<br/>

Barnacle removals were carried out for the central 15 x 15 cm area of each plot; to do so, adult barnacles and any associated species were chiselled off the substratum, and subsequently scraped away with a putty knife to render the substratum almost entirely devoid of macroscopic life. The removed barnacle bed was collected and preserved (in 70% ethanol) from eight haphazardly selected plots to allow characterization of the infaunal community prior to the onset of summer temperatures.

<br/>

iButton temperature loggers were installed on the substratum using A-788 Splash Zone epoxy (Pettit Paints, NJ, USA) in all treatments within five randomly chosen blocks to measure differences in temperatures between treatments.

<br/>

Visual surveys were performed at the time of installation (for intact treatments), early July 2021, and late August 2021. At the end of the experimental period, all UI and SI treatment plots were destructively sampled, and these were preserved in 70% ethanol to characterize the infaunal community. Species were identified and enumerated as with other barnacle bed samples.

## Statistical analyses

<br/>



# Results

<br/>

# Figures

<br/>

# Figure legends

<br/>

**Figure 1.** Map of sites surveyed during study. Symbols associated with each site indicate what data were collected at the site (‡ = mortality, • = substratum orientation,  ¿ = infauna composition)

<br/>

**Figure 2.** Mean number of infaunal taxa counted within _S. cariosus_ beds at each site. Different colours indicate coarse taxonomic groupings, and error bars indicate the standard error about the mean.

<br/>

**Figure 3.** The relationship between the percentage mortality of _S. cariosus_ observed during mortality surveys and the dominant shore aspect at the survey site. Color represents the average air temperature experienced during low tide over the period of the Pacific Northwest Heat Dome (25-29 June, 2021). The trendline represents values predicted by the generalized linear model.

<br/>

**Figure 4.** The effect of substratum orientation on percentage mortality of _S. cariosus_. Color represents the site at which data were recorded, and the trendline represents the overall effect of substratum orientation on mortality predicted by the generalized linear model.

<br/>

**Figure 5.** **(A)** The effect of shading treatment on the survival of S. cariosus in intact barnacle beds. **(B)** The effect of shading treatment and barnacle bed presence/absence on the recruitment of acorn barnacles (_S. cariosus_, _B. glandula_, and _C. dalli_).

<br/>

**Figure 6.** nMDS plot showing differences in infaunal community composition between shaded and unshaded _S. cariosus_ barnacle beds.

# Discussion

# Acknowledgements

# References

