---
title: "Semibalanus infaunal gradient"
author: "Amelia Hesketh"
date: "06/10/2021"
output: html_document
---

```{r, results = 'hide', echo = F, message = F}
# load packages
pkgs <- c("vegan", "vegan3d", "tidyverse", "RColorBrewer", "plotrix", "glmmTMB", "viridis", "patchwork", "magick", "ggpubr", "wesanderson")
invisible(lapply(pkgs, library, character = T))
rm(pkgs)

# load relevant data: collection info (associates number of collection with site code and collection date)
collection.info <- read_csv("../raw_data/infauna/SBHW_INFAUNA_collections.csv")
# load taxonomic data: contains information about taxonomic groupings and authorities, species codes, etc.
taxonomic.info <- read_csv("../raw_data/SBHW_taxonomic_20220105.csv") %>%  select(original_code, final_code, coarse_grouping)

# will need to read all the files for all collections ... list all the file names in this directory for reading in
sample.files <- list.files("../raw_data/infauna/community_data/")

# this loop takes a file and loads it in, capturing information about the collection number from the numeric component of the file namem, and joins these in wide format
for (file in 1: length(sample.files)){
  
  file.name = paste("../raw_data/infauna/community_data/", sample.files[file], sep = "")
  
  infauna <- read_csv(file.name)
  
  # these data contain taxa at their lowest recorded taxonomic level
  infauna.sum <- infauna %>% mutate(replicate = seq(1:nrow(infauna))) %>% 
    pivot_longer(cols = -replicate, names_to ="original_code", values_to = "abundance") %>% 
    left_join(taxonomic.info) %>% 
    select(-original_code) %>% 
    group_by(replicate, final_code) %>% summarize(abundance = sum(abundance)) %>% 
    pivot_wider(names_from = final_code, values_from = abundance) %>% mutate(file_name = sample.files[file])
  
  # these data are for coarse taxonomic groupings
  infauna.coarse <- infauna %>% 
    pivot_longer(cols = 1:ncol(infauna), names_to ="original_code", values_to = "abundance") %>% 
    left_join(taxonomic.info) %>% 
    select(-original_code, -final_code) %>% 
    group_by(coarse_grouping) %>% summarize(mean.abund = mean(abundance),se.abund = std.error(abundance)) %>% mutate(file_name = sample.files[file])
  
  if (file == 1){
    infauna.all <- infauna.sum
    infauna.all.coarse <- infauna.coarse
  }
  if (file > 1){
    infauna.all <- infauna.sum %>% full_join(infauna.all)
    infauna.all.coarse <- infauna.coarse %>% full_join(infauna.all.coarse)
  }
}
```

#nMDS Analysis

```{r}
## start with the nmds analysis to visualize differences between sites
# this will go in the supplemental, but the PERMANOVA results can go in the main text

infauna.clean <- infauna.all %>% replace(is.na(.), 0) %>% separate(file_name, c("code", "data", "collection_number"), sep = "_") %>% select(-code, -data) %>% mutate(collection_number = as.numeric(str_remove_all(collection_number, ".csv"))) %>% left_join(collection.info)

# bring in color palette from maps script
palette <- site_info %>% select(site_code, full.pal)

# filter by time: only collections made at the end of summer 2021 (NOT 1 and 2)
infauna.summer <- infauna.clean %>% filter(collection_number %in% 3:12) %>% left_join(palette)
col.levels <- infauna.summer$full.pal %>% unique()
site.levels <- infauna.summer$site_code %>% unique()

#get rid of everything not related to species abundance and convert to matrix for nMDS
infauna.matrix <- infauna.summer %>% ungroup() %>% 
  select(-collection_number, -site_code, -collection_date, -full.pal, -replicate) 
  
# convert to matrix
infauna.matrix <- as.matrix(infauna.matrix)

# ready to analyze
comm.infauna <- metaMDS(infauna.matrix, k = 3, try = 999, autotransform = T)
stressplot(comm.infauna) # plot stress
comm.infauna$stress # print stress of final model (ok with 2 dimensions, but not excellent)
# if you try replotting with 3 dimensions, stress is <0.2, so better to have all 3

#PERMANOVA
adonis(infauna.matrix~site_code, data = infauna.summer)

dist <- vegdist(infauna.matrix, method = "bray")
gradient.beta <- betadisper(dist, group = infauna.summer$site_code, bias.adjust = T)
anova(gradient.beta)

```
```




```
```{r, echo=F, fig.align='center', fig.keep = "last", fig.show = "asis", message=FALSE, results=F, fig.dim = c(9,7)}

## ggplot of first two NMDS axes

data.scores <- as.data.frame(scores(comm.infauna))
data.scores$site_code <- infauna.summer$site_code

data.scores <- data.scores %>% group_by(site_code) %>% mutate(mean.x = mean(NMDS1), mean.y = mean(NMDS2)) %>% ungroup() %>% mutate(site_code = factor(site_code, levels = site.levels))

species.scores <- as.data.frame(scores(comm.infauna, "species"))
species.scores$species <- rownames(species.scores) 

infauna.ordination <- ggplot() + 
  geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=site_code),size=3, alpha = 0.8) + # add the point markers
  geom_text_repel(data=species.scores,aes(x=NMDS1,y=NMDS2,label=species),size = 2.5, alpha=0.7,
                  max.overlaps = 500, box.padding=0.05, min.segment.length = 5) +
  coord_equal() +
  theme_bw() +
  scale_color_manual(values = col.levels) +
  geom_segment(aes(x = NMDS1, y = NMDS2, xend = mean.x, yend = mean.y, col = site_code), data = data.scores, alpha = 0.7) +
  geom_text(data=data.scores,aes(x=mean.x, mean.y,label=site_code),size=4, alpha = 0.7, col = "grey20" ) +  # add the site labels 
  #geom_text(aes(x = 0.9, y = 0.6, label = paste("Stress = ", round(comm.infauna$stress,4))),cex = 4) +
  labs(color = "Site code", x = "Axis 1", y = "Axis 2") +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))

infauna.ordination
ggsave(filename = "../outputs/S1Fig2.png", infauna.ordination, dpi = 1200)

```



This plot instead looks at # taxa defined by coarse groupings.

```{r, results = T}

site.levels <- as.data.frame(c("WBS","PP","BO","KE","TP","SP","SA","SN","TE","TK")) %>% rename(site_code = 1) 
col.conversion <- site.levels %>% left_join(site_info) %>% select(full.pal)
col.levels <- col.conversion$full.pal
site.levels <- site.levels$site_code
pal <- wes_palette("Darjeeling2", n = 16, type = "continuous")

infauna.clean.coarse <- infauna.all.coarse %>% 
  separate(file_name, c("code", "data", "collection_number"), sep = "_") %>% select(-code, -data) %>% mutate(collection_number = as.numeric(str_remove_all(collection_number, ".csv"))) %>% left_join(collection.info) %>% filter(collection_number %in% c(3:12)) %>% select(-collection_date, -collection_number) %>% mutate(site_code = factor(site_code, levels = site.levels), coarse_grouping = fct_reorder(coarse_grouping, mean.abund, max))


barplot.abund <- ggplot(aes(x = site_code, fill = coarse_grouping, y = mean.abund), 
                  data = infauna.clean.coarse) +
  geom_bar(position = "stack", stat = "identity", col = "grey50", lwd = 0.2, width = 0.8) +
  theme_classic() +
  labs(y = "Mean abundance", x = "Collection site", fill = "Taxon") +
  scale_fill_discrete(type = pal) +
  theme(axis.title = element_text(size = 24), axis.text = element_text(size = 20),
        legend.title=element_text(size = 24), legend.text = element_text(size = 20))
barplot.abund

ggsave(filename = "../outputs/Fig2C.png", barplot.abund, dpi = 1200, width = 14, height = 7, units = "in")

```

```{r}

# how many taxa @ each site?

# get Shannon diversity and richness from matrix
H <- diversity(infauna.matrix, "shannon")

infauna.richness <- infauna.summer %>% select(site_code, replicate)
richness <- with(infauna.richness, specnumber(infauna.matrix))

# join with data to incude informative factors
infauna.diversity <- cbind(cbind(infauna.summer, richness),H) %>% rename(richness = 56, Shannon_diversity = 57) %>% mutate(site_code = factor(site_code, levels = site.levels))

infauna.div.summary <- infauna.diversity %>% group_by(site_code, full.pal) %>% summarize(mean.rich = mean(richness), se.rich = std.error(richness), mean.H = mean(Shannon_diversity), se.H = std.error(Shannon_diversity)) %>% mutate(site_code = factor(site_code, levels = site.levels))

color.col <- arrange(infauna.diversity, by_group = site_code) %>% ungroup() %>% select(full.pal) %>% unique()
col.levels <- color.col$full.pal

infauna.div.summary2 <- infauna.div.summary %>% mutate(full.pal = factor(full.pal, levels = col.levels))

diversity.plot <- ggplot(aes(x = site_code, y = H, fill = site_code), data = infauna.diversity) +
  #geom_bar(stat = "identity", position = "dodge", width = 0.8) +
  #geom_errorbar(aes(ymax = mean.H + se.H, ymin = mean.H-se.H), width = 0.2) +
  geom_boxplot() +
  labs(x = "Collection site", y = "Shannon diversity") + 
  scale_fill_manual(values = col.levels) +
  theme_classic()+
  theme(axis.title = element_text(size = 24), axis.text = element_text(size = 20), legend.position = "none")
diversity.plot

ggsave(filename = "../outputs/Fig2B.png", diversity.plot, dpi = 1200)

# final panel: species richness, color coded by site
View(infauna.diversity$richness)
richness.plot <- ggplot(aes(x = site_code, y = richness, fill = site_code), data = infauna.diversity) +
  #geom_bar(stat = "identity", position = "dodge", width = 0.8) +
  #geom_errorbar(aes(ymax = mean.rich + se.rich, ymin = mean.rich-se.rich), width = 0.2) +
  geom_boxplot() +
  labs(x = "Collection site", y = "Species richness") + 
  scale_fill_manual(values = col.levels) +
  theme_classic()+
  theme(axis.title = element_text(size = 24), axis.text = element_text(size = 20), legend.position = "none")
richness.plot

ggsave(filename = "../outputs/Fig2A.png", richness.plot, dpi = 1200)

infauna.photo <- image_convert(image_read("../infauna.jpg"), "png")

photo.plot <- ggdraw() + draw_image(infauna.photo) + theme(plot.margin = margin(0,0,0,0))

Fig2 <- (richness.plot | diversity.plot) / (barplot.abund | photo.plot) +
 plot_annotation(tag_levels = "A") & theme(plot.tag =element_text(size = 26, face = "bold")) 

ggsave(Fig2, filename = "../outputs/Fig2.png", dpi = 1200, height = 5, width = 7, units = "in", scale = 2.5)

```


## NMDS plot of infauna seasonal shift

```{r}

infauna.shift <- infauna.clean %>% filter(collection_number %in% c(1,2,10,12))

#get rid of everything not related to species abundance and convert to matrix for nMDS
infauna.matrix <- infauna.shift %>% ungroup() %>% 
  select(-collection_number, -site_code, -collection_date, -replicate)


# convert to matrix
infauna.matrix <- as.matrix(infauna.matrix)

# ready to analyze
comm.infauna <- metaMDS(infauna.matrix, k = 3, try = 999, autotransform = T)
comm.infauna$stress # print stress of final model (ok with 2 dimensions, but not excellent)
# stress is < 0.2 with 3 dimensions.

#PERMANOVA

adonis(infauna.matrix~ site_code*collection_date, data = infauna.shift)
# one site shifted more than the other!

dist <- vegdist(infauna.matrix, "bray")

infauna.beta <- betadisper(dist, infauna.shift$collection_number, bias.adjust = T)
anova(infauna.beta)

```


# plot

```{r}
## ggplot of first two NMDS axes

data.scores <- as.data.frame(scores(comm.infauna))
data.scores$treatment <- infauna.shift$collection_number

data.scores <- data.scores %>% group_by(treatment) %>% mutate(mean.x = mean(NMDS1), mean.y = mean(NMDS2)) %>% ungroup() %>% mutate(treatment = case_when(treatment == "1" ~ "PP April 2021",treatment == "2" ~ "SA April 2021", treatment == "10" ~ "SA August 2021", treatment == "12" ~ "PP September 2021"))

species.scores <- as.data.frame(scores(comm.infauna, "species"))
species.scores$species <- rownames(species.scores) 

## adding ellipses to plot

veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
  {
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
  }

  df_ell <- data.frame()
  for(g in levels(as.factor(data.scores$treatment))){
    df_ell <- rbind(df_ell, cbind(as.data.frame(with(data.scores[data.scores$treatment==g,],
                    veganCovEllipse(cov.wt(cbind(NMDS1,NMDS2),wt=rep(1/length(NMDS1),length(NMDS1)))$cov,center=c(mean(NMDS1),mean(NMDS2)))))
                    ,group=g))
  }

df_ell$treatment <- df_ell$group

library(ggrepel)
## create ggplot ordination
infauna.ordination.shift <- ggplot() + 
  geom_path(data=df_ell,aes(x = NMDS1,y =NMDS2,colour=treatment)) +
  geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=treatment),size=3, alpha = 0.8) + # add the point markers
  geom_text_repel(data=species.scores,aes(x=NMDS1,y=NMDS2,label=species),size = 4, alpha=0.7,
                  max.overlaps = 500, box.padding=0.05, min.segment.length = 5) +
  coord_equal() +
  theme_bw() +
  labs(color = "Collection", x = "Axis 1", y = "Axis 2") +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  annotate("text", x = -0.5, y = -1.6, label = "Stress = 0.1343", size = 5) +
  scale_color_manual(values = c("#528ad9", "#9D7426", "#a9d672", "#CEAA07"))
infauna.ordination.shift

ggsave(filename = "../outputs/S1Fig9.png", infauna.ordination.shift, dpi = 1200,
       width = 3.5, height = 2.5, units = "in", scale = 2)

adonis(infauna_abund ~ treatment, infauna_factors)

```


