---
title: "Shade experiment analyses: surveys"
author: "Amelia Hesketh"
date: "29/10/2021"
output: html_document
---

## Assembling data

```{r}

library(tidyverse)

taxa <- read_csv("../raw_data/SBHW_taxonomic_20220105.csv") %>%  select(original_code, final_code, kingdom)
plots <- read_csv("../raw_data/shade/SBHW_SHADE_plot_info.csv")

viz.1 <- read_csv("../raw_data/shade/SBHW_SHADE_visual_1_20210414.csv") %>% pivot_longer(cols = 4:length(.), names_to = "original_code", values_to = "abund") %>% left_join(plots) %>% select(date, block, plot_number, original_code, abund, treatment_original_numeric) %>% right_join(taxa) %>% na.omit %>% rename(treatment = treatment_original_numeric)

viz.2 <- read_csv("../raw_data/shade/SBHW_SHADE_visual_2_20210708.csv") %>% pivot_longer(cols = 4:length(.), names_to = "original_code", values_to = "abund") %>% left_join(plots) %>% select(date, block, plot_number, original_code, abund, treatment_original_numeric) %>% right_join(taxa) %>% na.omit %>% rename(treatment = treatment_original_numeric)

viz.3 <- read_csv("../raw_data/shade/SBHW_SHADE_visual_3_202108.csv") %>% pivot_longer(cols = 4:length(.), names_to = "original_code", values_to = "abund") %>% left_join(plots) %>% mutate(date = as.Date("2021-08-21")) %>% select(date, plot_number, block, original_code, abund, treatment_original_numeric) %>% right_join(taxa) %>% na.omit %>% rename(treatment = treatment_original_numeric)

all_visuals <- viz.1 %>% full_join(viz.2) %>% full_join(viz.3) %>% mutate(treatment_code = case_when(treatment == 1 ~ "UI", treatment == 2 ~ "SI", treatment == 3 ~ "UR", treatment == 4 ~ "SR")) %>% select(-original_code)

write_csv(all_visuals, "../clean_data/SBHW_shade_visual_clean.csv")

# all the data is now collated!

# next, collate the infaunal surveys

collections <- read_csv("../raw_data/infauna/SBHW_INFAUNA_collections.csv")

file.list <- list.files("../raw_data/infauna/community_data", full.names = T)

for (i in 1:length(file.list)){
  df <- read_csv(file.list[i]) %>% mutate(collection_number = as.numeric(gsub("[^0-9]", "",file.list[i])))

  if (i == 1){
      df_all <- df
  }
  
  if (i > 1){
    df_all <- df_all %>% full_join(df) #%>% mutate_all(~replace_na(.,0))
  }
}

infauna_all <- df_all %>% mutate_all(~replace_na(., 0)) %>% relocate(collection_number, .before = MYSP) %>% left_join(collections) %>% relocate(c(site_code, collection_date), .after = (collection_number))

write_csv(infauna_all, "../clean_data/SBHW_infauna_clean.csv")

```

## Plotting & modeling

```{r}

library(glmmTMB)
library(DHARMa)
library(car)

# PLOT/ANALYSIS 1: Barnacle recruitment in unshaded plot

barnacles <- all_visuals %>% filter(final_code %in% c("BAGL","CHDA", "SECA") & treatment %in% c(3, 4)) %>% mutate(date = as.Date(date))

summary.bncles <- all_visuals %>% group_by(date) %>% summarize(bncle_total = sum(abund))

# middle survey has the most recruitment signal

recruitment.peak <- barnacles %>% filter(date == "2021-07-07" | date == "2021-07-08") %>% group_by(plot_number, block, treatment_code) %>% summarize(total_abund = sum(abund)) 

fig5d <- ggplot(recruitment.peak, aes(x = treatment_code, y = total_abund, fill =  treatment_code, col =  treatment_code)) + geom_boxplot(alpha = 0.4, outlier.shape = NA) + geom_jitter(width = 0.2, alpha = 0.3) + labs(x = "Treatment", y = "Total barnacle abundance", fill = "Treatment") + theme_classic() + scale_fill_manual(values = c("skyblue3", "tomato2")) + scale_color_manual(values = c("skyblue3", "tomato2")) + theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.position = "none")

mod.recruit <- glmmTMB(total_abund ~ treatment_code + (1|block), data = recruitment.peak,
                       family = nbinom2())

plot(simulateResiduals(mod.recruit))
summary(mod.recruit)
Anova(mod.recruit)

```

## Diversity over time

```{r}
library(vegan)
library(lubridate)
library(lme4)
library(plotrix)
library(glmmTMB)
library(patchwork)

# 1: species richness over time, whole community via visual surveys

visuals.whole <- all_visuals %>% 
  select(-kingdom, -treatment) %>% 
  pivot_wider(names_from = final_code, values_from = abund) %>% 
  replace(is.na(.), 0) 


richness.whole <- visuals.whole %>% select(5:length(.)) %>% as.matrix %>% specnumber() %>% 
  cbind(visuals.whole[,1:4]) %>% as.data.frame() %>% rename(richness = 1) %>% mutate(date = as.Date(str_replace_all(date,"2021-07-07","2021-07-08")))

richness.summary <- richness.whole %>% group_by(date, treatment_code) %>% summarize(mean.rich = mean(richness), se.rich = std.error(richness)) 

## plot

ggplot(richness.summary, aes(x = date, y = mean.rich, col = treatment_code)) +
  geom_point() +
  geom_errorbar(aes(ymax = mean.rich + se.rich, ymin = mean.rich - se.rich), width = 2) +
  scale_color_manual(values = c("skyblue4","skyblue2", "tomato4", "tomato2"))
  
## model

# first, inspect distribution of groups to assess best modeling approach

richness.final <- richness.whole %>% filter(date > "2021-08-01") %>% 
  separate(treatment_code, c("shading","removal"), 1, remove = F)

ggplot(richness.final, aes(y = richness, fill = treatment_code)) +
  geom_histogram()+
  facet_wrap(~treatment_code)

richness.model <- glmmTMB(richness ~ shading*removal + (1|block), data = richness.final,
                          family = poisson(link = "log"))
simulationOutput <- simulateResiduals(richness.model)
plot(simulationOutput)
testDispersion(simulationOutput) # slight underdispersion. proceed with model

summary(richness.model)
Anova(richness.model, type = 3)

# plot of richness @ last timept

fig5e <- ggplot(richness.whole, aes(x = treatment_code, y = richness, fill = treatment_code, col = treatment_code)) + geom_boxplot(alpha = 0.4, outlier.color = NA) + geom_jitter(alpha = 0.3, width = 0.2) + scale_color_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2")) + scale_fill_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2"))+ theme_classic() + theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.position = "none") + labs(x = "Treatment", y = "Species richness")

```

# plots continued

```{r}

visuals_inverts <- all_visuals %>% 
  filter(kingdom == "Animalia") %>% 
  select(-kingdom, -plot_number, -treatment) %>% 
  pivot_wider(names_from = final_code, values_from = abund) %>% 
  replace(is.na(.), 0) 

visuals_factors <- visuals_inverts %>% select(1:3)

visuals_species <- visuals_inverts %>% select(4:length(.)) %>% as.matrix 

H.inverts <- diversity(visuals_species, index = "shannon")

shannon.inverts <- as.data.frame(cbind(visuals_factors, H.inverts)) %>% rename(shannon = 4) %>% filter(date > "2021-08-01") %>% # just take last day
separate(treatment_code, c("shading","removal"),1, remove = F)
  
ggplot(aes(y = shannon), data = shannon.inverts) +
  geom_histogram()+ facet_wrap(~treatment_code)

diversity.inverts.lmer <- glmmTMB(shannon ~ shading*removal + (1|block), data = shannon.inverts)

AIC(diversity.inverts.lmer, diversity.inverts.lmer.1)
plot(simulateResiduals(diversity.inverts.lmer))
summary(diversity.inverts.lmer)
Anova(diversity.inverts.lmer, type = 3)

fig5f <- ggplot(shannon.inverts, aes(x = treatment_code, y = shannon, fill = treatment_code, col = treatment_code)) + geom_boxplot(alpha = 0.4, outlier.color = NA) + geom_jitter(alpha = 0.3, width = 0.2) + scale_color_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2")) + scale_fill_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2"))+ theme_classic() + theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.position = "none") + labs(x = "Treatment", y = "Shannon diversity (invertebrates)")

## and now repeat for algae

visuals_algae <- all_visuals %>% 
  filter(kingdom != "Animalia") %>% 
  select(-kingdom, -plot_number, -treatment) %>% 
  pivot_wider(names_from = final_code, values_from = abund) %>% 
  replace(is.na(.), 0) 

visuals_factors <- visuals_algae %>% select(1:3)

visuals_species <- visuals_algae %>% select(4:length(.)) %>% as.matrix 

H.algae <- diversity(visuals_species, index = "shannon")

shannon.algae <- as.data.frame(cbind(visuals_factors, H.algae)) %>% rename(shannon = 4) %>% filter(date > "2021-08-01") %>% # just take last day
separate(treatment_code, c("shading","removal"),1, remove = F)
  
ggplot(aes(y = shannon), data = shannon.algae) +
  geom_histogram()+ facet_wrap(~treatment_code) # a LOT of zeroes in these data

diversity.algae.lmer <- glmmTMB(shannon ~ shading*removal + (1|block), family = tweedie(link = "log"), data = shannon.algae)
plot(simulateResiduals(diversity.algae.lmer))
summary(diversity.algae.lmer)
Anova(diversity.algae.lmer, type = 3)

S1F5 <- ggplot(shannon.algae, aes(x = treatment_code, y = shannon, fill = treatment_code, col = treatment_code)) + geom_boxplot(alpha = 0.4, outlier.color = NA) + geom_jitter(alpha = 0.3, width = 0.2) + scale_color_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2")) + scale_fill_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2"))+ theme_classic() + theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.position = "none") + labs(x = "Treatment", y = "Shannon diversity (algae)")

## algal cover
algal_cover <-  all_visuals %>% filter(kingdom != "Animalia") %>% select(-kingdom, -plot_number, -treatment) %>% filter(date > "2021-08-01") %>% group_by(block, treatment_code) %>% summarize(cover = sum(abund)) %>% separate(treatment_code, c("shading","removal"),1, remove = F) 

algal_cover.tr <- algal_cover %>% mutate(cover = (cover*(nrow(algal_cover)-1)+0.5)/nrow(algal_cover)) 

cover.algae.glmm <- glmmTMB(cover ~ shading*removal + (1|block), family = beta_family(link = "logit"), data = algal_cover.tr)
plot(simulateResiduals(cover.algae.glmm))
summary(cover.algae.glmm)
Anova(cover.algae.glmm, type = 3)

S1F5b <- ggplot(algal_cover, aes(x = treatment_code, y = cover*100, fill = treatment_code, col = treatment_code)) + geom_boxplot(alpha = 0.4, outlier.color = NA) + geom_jitter(alpha = 0.3, width = 0.2) + scale_color_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2")) + scale_fill_manual(values = c("skyblue4","skyblue3", "tomato4", "tomato2"))+ theme_classic() + theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.position = "none") + labs(x = "Treatment", y = "Algal cover (%)")
S1F5b

library(patchwork)

# assemble figure

layout <- "
AAAABBBB
CCDDEEFF
"

fig5 <- fig5a + fig5b + fig5c + fig5d + fig5e + fig5f + plot_layout(guides = "collect", design = layout, nrow = 2) + plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold"))

ggsave(fig5, filename = "../outputs/Fig5.png", dpi = 1200, width = 7, height = 5, units = "in", scale = 1.5) 

```


## Infauna matrix

```{r}

set.seed(4947)

```


## Infauna at Sahsima only

```{r}
plot.info <- read_csv("../raw_data/shade/SBHW_SHADE_plot_info.csv")

infauna_sa.1 <- read_csv("../raw_data/shade/SBHW_SHADE_infauna.csv") %>% rename(plot_number = plot_id) %>%  left_join(plot.info) %>% select( -treatment_final_numeric, -shore_level) %>% rename(treatment = treatment_original_numeric)

infauna_sa <- infauna_sa.1 %>% select(-plot_number)

infauna_factors <- infauna_sa %>% select(treatment, block)
infauna_matrix <- infauna_sa %>% select(-treatment, -block) %>% as.matrix()

infauna_bray <- invisible(metaMDS(infauna_matrix, k=2, try = 999, autotransform = T))
infauna_bray$stress

# only non-rare species (>5 individuals)

abund.spec <- as.data.frame(colSums(infauna_matrix)) %>% rename(total = 1) %>% filter(total >= 5) %>% rownames()
infauna_abund <- infauna_matrix[,abund.spec]

infauna_bray_abund <- invisible(metaMDS(infauna_abund, k=2, try = 999, autotransform = T))


```


```{r}

## ggplot of first two NMDS axes

data.scores <- as.data.frame(scores(infauna_bray))
data.scores$treatment <- infauna_factors$treatment

data.scores <- data.scores %>% group_by(treatment) %>% mutate(mean.x = mean(NMDS1), mean.y = mean(NMDS2)) %>% ungroup() %>% mutate(treatment = case_when(treatment == "1" ~ "Unshaded",treatment == "2" ~ "Shaded"))

species.scores <- as.data.frame(scores(infauna_bray, "species"))
species.scores$species <- rownames(species.scores) 

## adding ellipses to plot

veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
  {
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
  }

  df_ell <- data.frame()
  for(g in levels(as.factor(data.scores$treatment))){
    df_ell <- rbind(df_ell, cbind(as.data.frame(with(data.scores[data.scores$treatment==g,],
                    veganCovEllipse(cov.wt(cbind(NMDS1,NMDS2),wt=rep(1/length(NMDS1),length(NMDS1)))$cov,center=c(mean(NMDS1),mean(NMDS2)))))
                    ,group=g))
  }

df_ell$treatment <- df_ell$group

library(ggrepel)
## create ggplot ordination
infauna.ordination.sa <- ggplot() + 
  geom_path(data=df_ell,aes(x = NMDS1,y =NMDS2,colour=treatment)) +
  geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=treatment),size=3, alpha = 0.8) + # add the point markers
  geom_text_repel(data=species.scores,aes(x=NMDS1,y=NMDS2,label=species),size = 4, alpha=0.7,
                  max.overlaps = 500, box.padding=0.05, min.segment.length = 5) +
  coord_equal() +
  theme_bw() +
  scale_color_manual(values = c("skyblue4","tomato4")) +
  #geom_text(aes(x = 0.9, y = 0.6, label = paste("Stress = ", round(comm.infauna$stress,4))),cex = 4) +
  labs(color = "Treatment", x = "Axis 1", y = "Axis 2") +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  annotate("text", x = -0.25, y = 1, label = "Stress = 0.1882", size = 5)
infauna.ordination.sa

ggsave(filename = "../outputs/Fig6.png", infauna.ordination.sa, dpi = 1200,
       width = 3.5, height = 2.5, units = "in", scale = 1.5)

adonis(infauna_matrix ~ treatment, infauna_factors)

dist <- vegdist(infauna_matrix, "bray")

infauna.beta <- betadisper(dist, infauna_factors$treatment)
anova(infauna.beta)

```

And let's do one more analysis to look at how the % mortality tracks with infauna abundance and diversity.

```{r}

mort.community <- infauna_sa.1 %>% full_join(barnacle.mort) %>% 
  relocate(c(treatment, block, prop_mort), .before = "DYSH") %>% 
  select(-plot_number, -number_live, -number_dead)

mort.matrix <- mort.community %>% select(-treatment, -block, -prop_mort) %>% as.matrix
mort.comm.factors <- mort.community %>% select(treatment,block,prop_mort)

H.inf <- diversity(mort.matrix)
rich.inf <- specnumber(mort.matrix)
abund.inf <- rowSums(mort.matrix)


mort.comm <- mort.comm.factors %>% cbind(H.inf) %>% cbind(rich.inf) %>% cbind(abund.inf) %>% na.omit() %>% mutate(treatment = as.factor(case_when(treatment == 1 ~ "Unshaded", treatment == 2 ~ "Shaded")), block = as.factor(block)) %>% filter(treatment == "Unshaded")

# just mortality in unshaded treatment (greatest range)
library(MASS)
mort.abund.mod <- glm.nb(abund.inf ~ prop_mort, data = mort.comm %>% filter(treatment == "Unshaded"), link = log) # using negative binomial due to overdispersion
plot(mort.abund.mod)
summary(mort.abund.mod)
anova(mort.abund.mod)


abund.pred <- predict(mort.abund.mod, mort.comm, type = "response", se.fit = T) 
mort.comm <- cbind(mort.comm, abund.pred) %>% rename(abund.pred = fit, abund.se = se.fit)

mort.abund <- ggplot(mort.comm %>% filter(treatment == "Unshaded"), aes(x = prop_mort*100, y = abund.inf)) + geom_point(size =3, col = "tomato4") + theme_classic()+theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 14)) + labs(x = expression(italic("S. cariosus")~"mortality (%)"), y = "Abundance") + geom_smooth(aes(y = abund.pred), method = "lm", col = "black", se = F) + geom_ribbon(aes(ymax = abund.pred + abund.se, ymin = abund.pred-abund.se), alpha = 0.2)

mort.abund

mort.H.mod <- lm(H.inf ~ prop_mort, data = mort.comm)
plot(mort.H.mod)
summary(mort.H.mod)
anova(mort.H.mod)

H.pred <- predict(mort.H.mod, mort.comm, type = "response", se.fit = T) 
mort.comm <- mort.comm %>% dplyr::select(-residual.scale) %>% cbind(H.pred) %>% rename(H.pred = fit, H.se = se.fit)

mort.H <- ggplot(mort.comm, aes(x = prop_mort*100, y = H.inf)) + geom_point(size = 3, col = "tomato4") + theme_classic()+theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 14)) + labs(x = expression(italic("S. cariosus")~"mortality (%)"), y = "Diversity") + geom_smooth(aes(y = H.pred), method = "lm", col = "black", se = F) + geom_ribbon(aes(ymax = H.pred + H.se, ymin = H.pred-H.se), col = NA, alpha = 0.2)


mort.H

mort.rich.mod <- glm(rich.inf ~ prop_mort, data = mort.comm, family = "poisson")
plot(simulateResiduals(mort.rich.mod))
summary(mort.rich.mod)
Anova(mort.rich.mod)

rich.pred <- predict(mort.rich.mod, mort.comm, type = "response", se.fit = T) 
mort.comm <- mort.comm %>% dplyr::select(-residual.scale, -df) %>% cbind(rich.pred) %>% rename(rich.pred = fit, rich.se = se.fit)

mort.rich <- ggplot(mort.comm, aes(x = prop_mort*100, y = rich.inf)) + geom_point(size = 3, col = "tomato4") + theme_classic()+theme(axis.title = element_text(size = 14), axis.text = element_text(size = 12), legend.text = element_text(size = 12), legend.title = element_text(size = 14)) + labs(x = expression(italic("S. cariosus")~"mortality (%)"), y = "Richness")  + geom_smooth(aes(y = rich.pred), method = "lm", col = "black", se = F) + geom_ribbon(aes(ymax = rich.pred + rich.se, ymin = rich.pred-rich.se), col = NA, alpha = 0.2)

mort.rich

fig6 <- infauna.ordination.sa + (mort.abund/mort.rich/mort.H) + plot_layout(guides = "collect", widths = c(4,2)) + plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold"))

ggsave(fig6, filename = "../outputs/Fig6.png", dpi = 1200, width = 7, height = 4, units = "in", scale = 1.5)

```

